<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFSpH7g6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFSpH7g6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFSpH7g6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFSpH7g6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFSpH7g6\App_KernelDevDebugContainer([
    'container.build_hash' => 'FSpH7g6',
    'container.build_id' => '19fc8b68',
    'container.build_time' => 1607436559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFSpH7g6');
