<?php

namespace ContainerFSpH7g6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7jtJXIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._7jtJXI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._7jtJXI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'errorValidator' => ['privates', 'App\\Services\\ErrorValidator', 'getErrorValidatorService', true],
            'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'serializer' => ['services', 'serializer', 'getSerializerService', false],
        ], [
            'entityManager' => '?',
            'errorValidator' => 'App\\Services\\ErrorValidator',
            'passwordEncoder' => '?',
            'serializer' => '?',
        ]);
    }
}
