<?php

namespace ContainerFSpH7g6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5B72mVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5B72m_V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5B72m_V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customLink' => ['privates', 'App\\Services\\CustomHateoasLinks', 'getCustomHateoasLinksService', true],
            'education' => ['privates', '.errored..service_locator.5B72m_V.App\\Entity\\Education', NULL, 'Cannot autowire service ".service_locator.5B72m_V": it references class "App\\Entity\\Education" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'errorValidator' => ['privates', 'App\\Services\\ErrorValidator', 'getErrorValidatorService', true],
        ], [
            'customLink' => 'App\\Services\\CustomHateoasLinks',
            'education' => 'App\\Entity\\Education',
            'em' => '?',
            'errorValidator' => 'App\\Services\\ErrorValidator',
        ]);
    }
}
