<?php

namespace ContainerFSpH7g6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xjf7dgPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xjf7dgP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xjf7dgP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'education' => ['privates', '.errored..service_locator.xjf7dgP.App\\Entity\\Education', NULL, 'Cannot autowire service ".service_locator.xjf7dgP": it references class "App\\Entity\\Education" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'education' => 'App\\Entity\\Education',
            'em' => '?',
        ]);
    }
}
