<?php

namespace ContainerFSpH7g6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X4NqLu9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X4NqLu9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X4NqLu9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'category' => ['privates', '.errored..service_locator.X4NqLu9.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.X4NqLu9": it references class "App\\Entity\\Category" but no such service exists.'],
            'customLink' => ['privates', 'App\\Services\\CustomHateoasLinks', 'getCustomHateoasLinksService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'errorValidator' => ['privates', 'App\\Services\\ErrorValidator', 'getErrorValidatorService', true],
        ], [
            'category' => 'App\\Entity\\Category',
            'customLink' => 'App\\Services\\CustomHateoasLinks',
            'em' => '?',
            'errorValidator' => 'App\\Services\\ErrorValidator',
        ]);
    }
}
