<?php

namespace ContainerFSpH7g6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8YYVF2DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8YYVF2D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8YYVF2D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customLink' => ['privates', 'App\\Services\\CustomHateoasLinks', 'getCustomHateoasLinksService', true],
            'project' => ['privates', '.errored..service_locator.8YYVF2D.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.8YYVF2D": it references class "App\\Entity\\Project" but no such service exists.'],
        ], [
            'customLink' => 'App\\Services\\CustomHateoasLinks',
            'project' => 'App\\Entity\\Project',
        ]);
    }
}
