<?php

namespace ContainerFSpH7g6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BM9B2SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BM9B_2S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BM9B_2S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customLink' => ['privates', 'App\\Services\\CustomHateoasLinks', 'getCustomHateoasLinksService', true],
            'skill' => ['privates', '.errored..service_locator.BM9B_2S.App\\Entity\\Skill', NULL, 'Cannot autowire service ".service_locator.BM9B_2S": it references class "App\\Entity\\Skill" but no such service exists.'],
        ], [
            'customLink' => 'App\\Services\\CustomHateoasLinks',
            'skill' => 'App\\Entity\\Skill',
        ]);
    }
}
