<?php

namespace ContainerFSpH7g6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomHateoasLinksService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\CustomHateoasLinks' shared autowired service.
     *
     * @return \App\Services\CustomHateoasLinks
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'CustomHateoasLinks.php';

        $a = ($container->services['router'] ?? $container->getRouterService());

        return $container->privates['App\\Services\\CustomHateoasLinks'] = new \App\Services\CustomHateoasLinks($a, $a, ($container->services['serializer'] ?? $container->getSerializerService()));
    }
}
