<?php

namespace ContainerFSpH7g6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExperience4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RVY637A.App\Entity\Experience' shared service.
     *
     * @return \App\Entity\Experience
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.RVY637A": it references class "App\\Entity\\Experience" but no such service exists.');
    }
}
