<?php

namespace ContainerUgp3Qgq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BrJNtP2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BrJNtP2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BrJNtP2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customLink' => ['privates', 'App\\Services\\CustomHateoasLinks', 'getCustomHateoasLinksService', true],
            'education' => ['privates', '.errored..service_locator.BrJNtP2.App\\Entity\\Education', NULL, 'Cannot autowire service ".service_locator.BrJNtP2": it references class "App\\Entity\\Education" but no such service exists.'],
        ], [
            'customLink' => 'App\\Services\\CustomHateoasLinks',
            'education' => 'App\\Entity\\Education',
        ]);
    }
}
