<?php

namespace ContainerUgp3Qgq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_12W2d9oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.12W2d9o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.12W2d9o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'project' => ['privates', '.errored..service_locator.12W2d9o.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.12W2d9o": it references class "App\\Entity\\Project" but no such service exists.'],
        ], [
            'em' => '?',
            'project' => 'App\\Entity\\Project',
        ]);
    }
}
