<?php

namespace ContainerUgp3Qgq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_40taaq1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.40taaq1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.40taaq1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customLink' => ['privates', 'App\\Services\\CustomHateoasLinks', 'getCustomHateoasLinksService', true],
            'experience' => ['privates', '.errored..service_locator.40taaq1.App\\Entity\\Experience', NULL, 'Cannot autowire service ".service_locator.40taaq1": it references class "App\\Entity\\Experience" but no such service exists.'],
        ], [
            'customLink' => 'App\\Services\\CustomHateoasLinks',
            'experience' => 'App\\Entity\\Experience',
        ]);
    }
}
