<?php

namespace ContainerUgp3Qgq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SxJ16W7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SxJ16W7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SxJ16W7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'software' => ['privates', '.errored..service_locator.SxJ16W7.App\\Entity\\Software', NULL, 'Cannot autowire service ".service_locator.SxJ16W7": it references class "App\\Entity\\Software" but no such service exists.'],
        ], [
            'software' => 'App\\Entity\\Software',
        ]);
    }
}
