<?php

namespace ContainerUgp3Qgq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EXGQunIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eXGQunI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eXGQunI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'education' => ['privates', '.errored..service_locator.eXGQunI.App\\Entity\\Education', NULL, 'Cannot autowire service ".service_locator.eXGQunI": it references class "App\\Entity\\Education" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'errorValidator' => ['privates', 'App\\Services\\ErrorValidator', 'getErrorValidatorService', true],
        ], [
            'education' => 'App\\Entity\\Education',
            'em' => '?',
            'errorValidator' => 'App\\Services\\ErrorValidator',
        ]);
    }
}
