<?php

namespace ContainerUgp3Qgq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ErrorValidator' shared autowired service.
     *
     * @return \App\Services\ErrorValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'ErrorValidator.php';

        return $container->privates['App\\Services\\ErrorValidator'] = new \App\Services\ErrorValidator(($container->services['validator'] ?? $container->load('getValidatorService')));
    }
}
