<?php

namespace ContainerUgp3Qgq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSoftware2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SxJ16W7.App\Entity\Software' shared service.
     *
     * @return \App\Entity\Software
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SxJ16W7": it references class "App\\Entity\\Software" but no such service exists.');
    }
}
